name: Create ZIP & Release

on: 
  workflow_dispatch:
    inputs:
      version: 
        description: "Version"
        default: "v1.0.0"
        required: true

permissions:
  contents: write

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.0

      - name: Prepare folder structure
        run: |
          mkdir -p homeassistant.koplugin
          mkdir -p icons
          cp main.lua config.lua _meta.lua homeassistant.koplugin/
          cp homeassistant.svg icons/

      - name: Create ZIP archive
        run: zip -r homeassistant.koplugin.zip homeassistant.koplugin icons

      - name: Upload Release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: "homeassistant.koplugin.zip"
          name: "homeassistant.koplugin.zip"
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
