name: Create ZIP & Release

on: 
  workflow_dispatch:
    inputs:
      version: 
        description: "Version"
        default: "v0.1.0"
        required: true

permissions:
  contents: write

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.0

      - name: Create ZIP archive
        run: zip homeassistant.koplugin.zip main.lua config.lua _meta.lua

      - name: Upload Release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: "homeassistant.koplugin.zip"
          name: "homeassistant.koplugin.zip"
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
